/* Bar functionality */
#include "bar_indicators.c"
#include "bar_tagicons.c"

#include "bar_alternativetags.c"
#include "bar_dwmblocks.c"
#include "bar_ewmhtags.c"
#include "combo.c"
#include "bar_ltsymbol.c"
#include "bar_status.c"
#include "bar_status2d.c"
#include "bar_statusbutton.c"
#include "bar_statuscmd.c"
#include "bar_tags.c"
#include "bar_wintitle.c"
#include "bar_systray.c"
#include "bar_layoutmenu.c"

/* Other patches */
#include "aspectresize.c"
#include "attachx.c"
#include "autostart.c"
#include "cfacts.c"
#include "cyclelayouts.c"
#include "decorationhints.c"
#include "dwmc.c"
#include "fakefullscreenclient.c"
#include "fullscreen.c"
#include "maximize.c"
#include "mpdcontrol.c"
#include "movestack.c"
#include "pertag.c"
#include "placemouse.c"
#include "rotatestack.c"
#include "roundedcorners.c"
#include "scratchpad.c"
#include "swallow.c"
#include "togglefullscreen.c"
#include "vanitygaps.c"
#include "xrdb.c"
#include "dragmfact.c"
/* Layouts */
#include "layout_facts.c"
#include "layout_bstack.c"
#include "layout_bstackhoriz.c"
#include "layout_centeredmaster.c"
#include "layout_centeredfloatingmaster.c"
#include "layout_columns.c"
#include "layout_monocle.c"
#include "layout_tile.c"
